version: '2.4'

services:
  server:
    build:
      context: ../
      dockerfile: docker/server.Dockerfile
      args:
        - UID=1000
    restart: always
    ports:
      - "8899:8899"
    volumes:
      - ../cache:/srv/cache
      - ../gbf_caching_proxy:/srv/server/
    command: uvicorn server:app --host 0.0.0.0 --port=8899 --workers=8 --reload